### ISSUE TITLE
Decline to Sign not implemented

### ISSUE THREAD

**Issue by davidmdavis** [docusign/docusign-ios-sdk#3]
Are there any plans to implement this feature? The Decline to Sign button is not currently implemented so when clicking the button, nothing happens.

``` objectivec
- (void)actionSheet:(UIActionSheet *)actionSheet clickedButtonAtIndex:(NSInteger)buttonIndex {
    if (actionSheet.tag == DSSigningViewControllerViewTagCancelSigning) {
        if (buttonIndex == actionSheet.destructiveButtonIndex) {
            // TODO: show decline modal
        } else if (buttonIndex == actionSheet.firstOtherButtonIndex) {
            [self changeSigningStatus:DSSigningCompletedStatusDeferred withObject:nil];
        }
    }
}
```

https://github.com/docusign/docusign-ios-sdk/blob/develop/DocuSign%20iOS%20SDK/SDK/Signing/DSSigningViewController.m#L456

**Comment by Ergin008** [comment]
Hi David, yes the iOS is still under development and is currently in BETA, though there are still integrations going live with it.  Since it's open source you are free to add the feature and submit a pull request and we can review and accept.  We have plans to take the SDK out of BETA but I don't have exact dates at the moment sorry.

**Comment by LarryKlugerDS** [comment]
Please accept my apologies for the extremely slow response to your issue.
We've now automated new processes so this won't happen again.

Meanwhile, this repo is now obsolete. Please see the README file for more information. Thank you.
